### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device (nms_cuda at /tmp/pip-req-build-8d3_7_rq/torchvision/csrc/cuda/nms_cuda.cu:127)

### ISSUE THREAD

**Issue by Leben-ls** [DataXujing/Pytorch_YOLO-v4#1]
Starting training for 300 epochs...

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     0/299     21.9G      6.73      1.39      2.72      10.8        26       320: 100%|█| 279/279 [02:26<00:00,  1.91it/s]
               Class    Images   Targets         P         R   mAP@0.5        F1:   0%|            | 0/76 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 409, in <module>
    train()  # train normally
  File "train.py", line 314, in train
    dataloader=testloader)
  File "/home/ly2/pytorch_YOLO/Pytorch_YOLO-v4/test.py", line 103, in test
    output = non_max_suppression(inf_out, conf_thres=conf_thres, iou_thres=iou_thres)  # nms
  File "/home/ly2/pytorch_YOLO/Pytorch_YOLO-v4/utils/utils.py", line 560, in non_max_suppression
    i = torchvision.ops.boxes.nms(boxes, scores, iou_thres)
  File "/home/ly2/miniconda3/envs/pytorch_python/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 33, in nms
    return _C.nms(boxes, scores, iou_threshold)

我的运行报错呀，请问这个是为什么呀？

**Comment by Leben-ls** [comment]
因为pytorch版本要在1.5以上，em。。。。

**Comment by DataXujing** [comment]
我的环境cuda 9.2, torch==1.3.0, torchvision==0.4.1，是没有问题的。出现这种问题，显然可能是你的torch和torchvision的版本和cuda和显卡驱动的版本不一致导致的。请检查你的cuda版本和显卡驱动版本与torch的编译的cuda版本是否保持一致，同时找到对应的torchvision版本进行安装；还有一种可能就是你的训练数据中有脏数据，请检查你的训练数据。从这两个方面入手，应该可以解决问题
